runtime: python39
instance_class: F1

handlers:
# Root level files (sitemap, robots, favicon, manifest & data file)
- url: /(.*\.(xml|txt|ico|json))
  static_files: \1
  upload: (.*\.(xml|txt|ico|json))
  expiration: "0"
  secure: always

# Service worker file
- url: /service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  mime_type: text/javascript
  expiration: "0"
  secure: always

# Static JS Files
- url: /static/(.*\.js)$
  static_files: static/\1
  upload: static/(.*\.js)
  mime_type: text/javascript
  secure: always
  expiration: "365d"
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff

# Other static files
- url: /static
  static_dir: static
  secure: always
  expiration: "365d"
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff

# Home Page
- url: /
  secure: always
  static_files: index.html
  upload: index.html
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Content-Security-Policy: default-src 'self' cloudflareinsights.com *.cloudflareinsights.com
    X-Content-Type-Options: nosniff

# All Other Pages
- url: /(.*)/
  secure: always
  static_files: \1/index.html
  upload: (.*)/index.html
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Content-Security-Policy: default-src 'self' cloudflareinsights.com *.cloudflareinsights.com
    X-Content-Type-Options: nosniff

# 404 Catcher
- url: /(.*)
  secure: always
  static_files: null/\1
  upload: null/(.*)
