runtime: python39

instance_class: F1

handlers:
# Root level files (sitemap, robots, favicon, manifest & data file)
- url: /(.*\.(xml|txt|ico|json))
  static_files: \1
  upload: (.*)
  secure: always

# Static Files
- url: /static
  secure: always
  static_dir: static
  expiration: "365d"
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: nosniff

# Home Page
- url: /
  secure: always
  static_files: index.html
  upload: index.html
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Content-Security-Policy: default-src 'self' cloudflareinsights.com *.cloudflareinsights.com
    X-Content-Type-Options: nosniff

# All Other Pages
- url: /(.*)/
  secure: always
  static_files: \1/index.html
  upload: (.*)/index.html
  http_headers:
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-Frame-Options: DENY
    X-XSS-Protection: 1; mode=block
    Content-Security-Policy: default-src 'self' cloudflareinsights.com *.cloudflareinsights.com
    X-Content-Type-Options: nosniff
