# Generated by Django 3.2.2 on 2021-05-10 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('wiki_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('wiki_link', models.URLField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mapsdata.book')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('wiki_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(height_field='height', upload_to='maps/', width_field='width')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('wiki_link', models.URLField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='mapsdata.continent')),
            ],
        ),
        migrations.CreateModel(
            name='RegionPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='X Coordinate')),
                ('y', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Y Coordinate')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_pointers', to='mapsdata.map')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_pointers', to='mapsdata.region')),
            ],
        ),
        migrations.CreateModel(
            name='ContinentPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='X Coordinate')),
                ('y', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Y Coordinate')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent_pointers', to='mapsdata.continent')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent_pointers', to='mapsdata.map')),
            ],
        ),
        migrations.CreateModel(
            name='CityPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.DecimalField(decimal_places=4, max_digits=5, verbose_name='X Coordinate')),
                ('y', models.DecimalField(decimal_places=4, max_digits=4, verbose_name='Y Coordinate')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_pointers', to='mapsdata.city')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_pointers', to='mapsdata.map')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='mapsdata.continent'),
        ),
    ]
