# Generated by Django 3.2.2 on 2021-05-10 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0003_auto_20210510_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='mapsdata.book'),
            preserve_default=False,
        ),
    ]
