# Generated by Django 3.2.2 on 2021-05-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0005_remove_city_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypointer',
            name='x',
            field=models.IntegerField(verbose_name='X Pixel'),
        ),
        migrations.AlterField(
            model_name='citypointer',
            name='y',
            field=models.IntegerField(verbose_name='Y Pixel'),
        ),
        migrations.AlterField(
            model_name='continentpointer',
            name='x',
            field=models.IntegerField(verbose_name='X Coordinate'),
        ),
        migrations.AlterField(
            model_name='continentpointer',
            name='y',
            field=models.IntegerField(verbose_name='Y Coordinate'),
        ),
        migrations.AlterField(
            model_name='regionpointer',
            name='x',
            field=models.IntegerField(verbose_name='X Coordinate'),
        ),
        migrations.AlterField(
            model_name='regionpointer',
            name='y',
            field=models.IntegerField(verbose_name='Y Coordinate'),
        ),
    ]
