# Generated by Django 3.2.2 on 2021-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0006_auto_20210511_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='continentpointer',
            name='x',
            field=models.IntegerField(verbose_name='X Pixel'),
        ),
        migrations.AlterField(
            model_name='continentpointer',
            name='y',
            field=models.IntegerField(verbose_name='Y Pixel'),
        ),
        migrations.AlterField(
            model_name='regionpointer',
            name='x',
            field=models.IntegerField(verbose_name='X Pixel'),
        ),
        migrations.AlterField(
            model_name='regionpointer',
            name='y',
            field=models.IntegerField(verbose_name='Y Pixel'),
        ),
    ]
