# Generated by Django 3.2.2 on 2021-05-14 14:05

from django.db import migrations, models
import mapsdata.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0007_auto_20210513_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='short_name',
            field=models.CharField(max_length=200, null=True, validators=[mapsdata.validators.validate_shortname]),
        ),
        migrations.DeleteModel(
            name='ContinentPointer',
        ),
    ]
