# Generated by Django 3.2.2 on 2021-05-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0008_auto_20210514_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='short_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
