# Generated by Django 3.2.2 on 2021-05-15 13:55

from django.db import migrations, models
import mapsdata.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0009_city_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_name',
            field=models.CharField(max_length=100, null=True, validators=[mapsdata.validators.validate_shortname]),
        ),
        migrations.AlterField(
            model_name='city',
            name='short_name',
            field=models.CharField(max_length=100, null=True, validators=[mapsdata.validators.validate_shortname]),
        ),
    ]
