# Generated by Django 3.2.2 on 2021-05-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0011_auto_20210516_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
