# Generated by Django 3.2.2 on 2021-05-18 18:43

from django.db import migrations, models
import mapsdata.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0013_alter_city_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='test', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='short_name',
            field=models.CharField(max_length=100, null=True, validators=[mapsdata.validators.validate_shortname]),
        ),
        migrations.AddField(
            model_name='continent',
            name='short_name',
            field=models.CharField(max_length=100, null=True, validators=[mapsdata.validators.validate_shortname]),
        ),
    ]
