# Generated by Django 3.2.2 on 2021-05-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0015_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(default='-', max_length=2000),
        ),
    ]
