# Generated by Django 3.2.2 on 2021-05-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0016_book_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='citymarker',
            constraint=models.UniqueConstraint(fields=('map', 'city'), name='unique_marker'),
        ),
    ]
