# Generated by Django 3.2.2 on 2021-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0017_citymarker_unique_marker'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='citymarker',
            name='unique_marker',
        ),
        migrations.AddConstraint(
            model_name='citymarker',
            constraint=models.UniqueConstraint(fields=('map', 'city'), name='unique_city_marker'),
        ),
        migrations.AddConstraint(
            model_name='regionmarker',
            constraint=models.UniqueConstraint(fields=('map', 'region'), name='unique_region_marker'),
        ),
    ]
