# Generated by Django 3.2.2 on 2021-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0018_auto_20210523_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='book',
        ),
        migrations.AddField(
            model_name='map',
            name='books',
            field=models.ManyToManyField(related_name='maps', to='mapsdata.Book'),
        ),
    ]
