# Generated by Django 3.2.2 on 2021-05-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0019_auto_20210524_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='continent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='mapsdata.continent'),
        ),
    ]
