# Generated by Django 3.2.2 on 2021-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0020_map_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='description',
            field=models.CharField(default='-', max_length=2000),
        ),
    ]
