# Generated by Django 3.2.2 on 2021-05-24 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0021_continent_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinentMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.IntegerField(verbose_name='X Pixel')),
                ('y', models.IntegerField(verbose_name='Y Pixel')),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent_markers', to='mapsdata.continent')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continent_markers', to='mapsdata.map')),
            ],
        ),
        migrations.AddConstraint(
            model_name='continentmarker',
            constraint=models.UniqueConstraint(fields=('map', 'continent'), name='unique_continent_marker'),
        ),
    ]
