# Generated by Django 3.2.2 on 2021-05-28 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mapsdata.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0022_auto_20210524_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('x', models.IntegerField(verbose_name='X Pixel')),
                ('y', models.IntegerField(verbose_name='Y Pixel')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='mapsdata.map')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100, null=True, validators=[mapsdata.validators.validate_shortname])),
                ('wiki_link', models.URLField()),
                ('description', models.CharField(default='-', max_length=2000)),
                ('type', models.CharField(choices=[('city', 'City'), ('region', 'Region')], max_length=6)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='mapsdata.continent')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CityMarker',
        ),
        migrations.DeleteModel(
            name='ContinentMarker',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RegionMarker',
        ),
        migrations.AddField(
            model_name='marker',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='mapsdata.place'),
        ),
        migrations.AddConstraint(
            model_name='marker',
            constraint=models.UniqueConstraint(fields=('place', 'map'), name='unique_place_marker'),
        ),
    ]
