# Generated by Django 3.2.2 on 2021-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0023_auto_20210528_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='maps/thumbnails/'),
        ),
    ]
