# Generated by Django 3.2.2 on 2021-06-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0024_map_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='maps/thumbnails/'),
        ),
    ]
