# Generated by Django 3.2.7 on 2021-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0026_auto_20210917_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Used to order maps when multiple maps are available for a place. Higher priority makes sure the maps is showed before other maps.'),
            preserve_default=False,
        ),
    ]
