# Generated by Django 3.2.7 on 2021-09-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0027_map_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Used to order maps when multiple maps are available for a place. Higher priority makes sure the maps is showed before other maps.'),
        ),
    ]
