# Generated by Django 3.2.7 on 2021-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapsdata', '0028_alter_map_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='map',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Higher priority makes sure the maps is showed before other maps.'),
        ),
    ]
