name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install yarn -g

      - name: Install packages
        run: yarn install

      - name: Build Static Site
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: www
          path: www

  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: www

      - name: Google App Engine Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          working_directory: www
