name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "views/**"
      - ".eleventy.js"
      - "esbuild.js"
      - "postcss.config.js"

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: tag
        run: echo "::set-output name=commit-tag::$(git describe)"

      - name: Install Yarn
        run: npm install yarn -g

      - name: Install packages
        run: yarn install

      - name: Build Static Site
        run: npm run build:prod

      - name: Google App Engine Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          working_directory: www
          version: ${{ steps.tag.outputs.commit-tag }}
